#!/usr/bin/node

const log = console.log;
log('CPU',process.arch);
log('OS:%s\n',process.platform);
log('PID',process.pid);
log('execPath:%s\n',process.execPath);

log('node.js ver:',process.version);
log('uid',process.getuid());
log('git,',process.getgid());
log('cwd:%s\n',process.cwd());

