#!/usr/bin/node

const log = console.log;
log('CPU',process.arch);
log('OS',process.platform);
log('PID',process.pid);
log('execPath',process.execPath);

log('node.js ver:',process.version);
log('uid',process.getuid());
log('git,',process.getuid());
/*process.stdin.on('data',function(data){

  console.log(data);
});*/
